create table invoices (
    amount float not null,
    created_at timestamp(6) not null,
    due_date date not null,
    id bigint generated by default as identity,
    subscription_id bigint not null,
    updated_at timestamp(6) not null,
    status varchar(255) not null,
    primary key (id)
);

create table payments (
    amount float not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    invoice_id bigint not null,
    payment_date timestamp(6),
    updated_at timestamp(6) not null,
    transaction_id varchar(255),
    status varchar(255) not null,
    primary key (id)
);

create table plans (
    is_active boolean not null,
    price float not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    description varchar(255),
    name varchar(255) not null,
    stripe_price_id varchar(255),
    billing_cycle varchar(255) not null,
    features varbinary(255),
    primary key (id)
);

create table subscriptions (
    auto_renew boolean not null,
    created_at timestamp(6) not null,
    current_period_end timestamp(6) not null,
    current_period_start timestamp(6) not null,
    id bigint generated by default as identity,
    plan_id bigint not null,
    updated_at timestamp(6) not null,
    user_id bigint not null,
    stripe_subscription_id varchar(255),
    status varchar(255) not null,
    primary key (id)
);

create table usage_records (
    quantity integer not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    recorded_at timestamp(6) not null,
    subscription_id bigint not null,
    updated_at timestamp(6) not null,
    action varchar(255) not null,
    primary key (id)
);

create table users (
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    updated_at timestamp(6) not null,
    company_name varchar(255),
    email varchar(255) not null,
    name varchar(255) not null,
    password varchar(255) not null,
    stripe_customer_id varchar(255),
    role varchar(255) not null,
    primary key (id)
);

alter table if exists users 
    add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);

alter table if exists invoices 
    add constraint FKpknahx679m51e06f97x8n1nd 
    foreign key (subscription_id) 
    references subscriptions;

alter table if exists payments 
    add constraint FK8qpmxex5m5ofk6m2q30uohhff 
    foreign key (invoice_id) 
    references invoices;

alter table if exists subscriptions 
    add constraint FKb1uf5qnxi6uj95se8ykydntl1 
    foreign key (plan_id) 
    references plans;

alter table if exists subscriptions 
    add constraint FKhro52ohfqfbay9774bev0qinr 
    foreign key (user_id) 
    references users;

alter table if exists usage_records 
    add constraint FKsf40cpjs77r0uhmiq6m6si3hy 
    foreign key (subscription_id) 
    references subscriptions;
